### ISSUE TITLE
Social Login: Apple missing errorDetails

### ISSUE THREAD

**Issue by SarahSteininger** [SAP/gigya-android-sdk#20]
gigya.login(socialProvider ...)

**Social Sign In with Apple:**
{"errorCode":206001,"errorMessage":"Account Pending Registration","regToken":"....."}

**Social Sign in with Google** (expected response containing missing fields):
{  "callId": "...",  "errorCode": 206001,  "errorDetails": "Missing required fields for registration: **country, preferences...**",  "errorMessage": "Account Pending Registration",  "apiVersion": 2,  "statusCode": 206,  "statusReason": "Partial Content",  "time": "2021-04-08T09:06:05.148Z",  "newUser": false,  "accountInfo": “ ...

**Comment by tal-mi** [comment]
Hi, 

Can you please provide a callID for that error?

**Comment by SarahSteininger** [comment]
Unfortunately there is no callId in the response when I try to login with apple as a provider. Below you find the whole response I get.
{"errorCode":206001,"errorMessage":"Account Pending Registration","regToken":"....."}

**Comment by tal-mi** [comment]
Do you have a network capture?

**Comment by SarahSteininger** [comment]
Network profiling data is unavailable.
<img width="872" alt="Screenshot 2021-04-20 at 14 43 53" src="https://user-images.githubusercontent.com/82881147/115397888-da2f1200-a1e6-11eb-9659-fb5edf09f4ab.png">

**Comment by tal-mi** [comment]
Network capture as in .har file? Using Filddler or Charles.
I will investigate this further.
Thanks.

Tal.

**Comment by SarahSteininger** [comment]
Thanks.
Moreover I would like to pass the missing consent upon social login as we do ask for the consent before calling login.
It seems that the consent I pass is completely ignored as the consent is still part of the missing fields in onPending. 

gigya.login(
                socialProvider, consent,
                object : GigyaLoginCallback<MyAccount>() { .....

**Comment by tal-mi** [comment]
Are u utilizing the "onPendingRegistration" callback to resolve it?
If you are looking to resolve your login flow given a missing fields error, we have provided this callback just for that.
The callback will return a IPendingRegistrationResolver class which can be used to call setAccount with the missing fields required for the process to end successfully.

To make sure you are receiving the missing fields make sure you add "missing-required-fields" to your "include" parameter.
Or use the [account config feature](https://github.com/SAP/gigya-android-sdk/tree/main/sdk-core#setting-account-configuration).

**Comment by SarahSteininger** [comment]
I know how to handle missing fields in onPending, however my question is why does passing the consent as a parameter of the login call not work.

When I call **register**, I can pass the consent in **params**.
<img width="620" alt="Screenshot 2021-04-21 at 09 59 54" src="https://user-images.githubusercontent.com/82881147/115518679-c0dea200-a288-11eb-80ec-873117062754.png">

If I try the same when I call **login with social provider**, the consent I pass as a parameter is ignored.
<img width="645" alt="Screenshot 2021-04-21 at 10 00 21" src="https://user-images.githubusercontent.com/82881147/115518917-fe432f80-a288-11eb-8212-3bbfebb5f5f4.png">

**Comment by tal-mi** [comment]
What kind of "consent" parameters are you passing through?

**Comment by SarahSteininger** [comment]
Terms of Service and other consent statements.
I wrap them inside a preferences map (for example: terms.myTerms.basic.isConsentGranted).

**Comment by tal-mi** [comment]
Thank you. Ill investigate the issue and update as soon as I can.

Tal

**Comment by tal-mi** [comment]
Hi,

The reason consent is not applied when using social login is because it is not supported via that specific endpoint.
It is recommended that you do it using setAccountInfo with the "regToken" you receive.
I will raise this issue with our backend team.

**Comment by SarahSteininger** [comment]
Thanks!
Actually what is expected to be passed when using social login? Without the consent I have nothing to pass, but passing an empty map is not supported (however this is possible in the swift SDK: _gigya.login(with: provider, viewController: viewController)_ ...).

java.lang.UnsupportedOperationException: Operation is not supported for read-only collection
        at kotlin.collections.EmptyMap.put(Unknown Source:4)
        at com.gigya.android.sdk.api.BusinessApiService.login(BusinessApiService.java:206)
        at com.gigya.android.sdk.Gigya.login(Gigya.java:388)

**Comment by tal-mi** [comment]
Social login requires the provider. Additional params may include "lang". Consent params are not supported.

Passing empty map to **Gigya.login** call is not supported cause you require to pass credentials in order to log in.

I suggest you go ahead and open a support case in order for us to properly address this issue.
https://developers.gigya.com/display/GD/Opening+A+Support+Incident

Tal.

**Comment by SarahSteininger** [comment]
Hi Tal,
Did you have any luck on figuring out why we get the error message without the missing fields?
I guess this issue is related to the non native webview logins as we are experiencing the same problem for iOS sign in on iOS < 12.

**Comment by tal-mi** [comment]
Are you providing "missing-required-fields" include parameter?

**Comment by SarahSteininger** [comment]
Yes, made no difference.

**Comment by tal-mi** [comment]
I will take this with our backend team and provide an update when available.

**Comment by SarahSteininger** [comment]
Thanks!

**Comment by tal-mi** [comment]
The issue has been moved to our backend team pipeline.
Will continue to update as it progresses into a resolution.
