### ISSUE TITLE
IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: 'nss_engine_id'

### ISSUE THREAD

**Issue by lo-g** [SAP/gigya-android-sdk#33]
Hi, from my crashlytics board I've noticed a certain number of this crash:

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{it.android.xxx/com.gigya.android.sdk.nss.NssActivity}: java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: 'nss_engine_id'
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3479)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3651)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
```
Caused by java.lang.IllegalStateException: The requested cached FlutterEngine did not exist in the FlutterEngineCache: 'nss_engine_id'
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:4)
       at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:4)
       at androidx.fragment.app.Fragment.performAttach(Fragment.java:2)
       at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:4)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:6)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:1)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:1)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:1)
       at io.flutter.embedding.engine.FlutterEngine.getDartExecutor(FlutterEngine.java)
       at android.app.Activity.performCreate(Activity.java:8109)
       at android.app.Activity.performCreate(Activity.java:8083)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3651)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:7861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Searching on internet I found this issue: [https://github.com/flutter/flutter/issues/51353](https://github.com/flutter/flutter/issues/51353), maybe moving this block before `super.onCreate(savedInstanceState)` will fix this crash? :

```
        engineLifeCycle = Gigya.getContainer().get(NssEngineLifeCycle::class.java)

        val ignitionData = intent?.extras?.getParcelable<IgnitionData>(EXTRA_DATA)
        ignitionData.guard {
            throw RuntimeException("Missing initialization data. Please verify that at least on the the NSS loading options has been provided (asset, hosted id).")
        }

        val engine = engineLifeCycle?.getNssEngine()
```

Unfortunately I'm not able to reproduce it directly...

Other info:
- Gigya core version: core-v5.1.5
- Android version: from 7 to 11
- 2% in background (of 105 crash)

**Comment by tal-mi** [comment]
What are you trying to do in your flow? Are you using the NSS engine?

**Comment by tal-mi** [comment]
Closing (obsolete)

**Comment by dermdaly** [comment]
We are seeing this in our app too.  It is the single biggest source of crashes. Looks like the Gigya NSS code is not correctly handling if an engine is in the cache or not. Could this bug be reopened?

**Comment by dermdaly** [comment]
FYI - This happened to us *again*.  And *again* during an app submission, causing a rejection.

**Comment by tal-mi** [comment]
This looks like a race condition in the NSSActivity lifecycle.

**Comment by tal-mi** [comment]
@dermdaly 
I have a potential fix for this issue. 
Do u have clear reproduction steps for verification?

**Comment by dermdaly** [comment]
I'm afraid we don't have a clear set of steps to reproduce - It is very likely a race condition. We could take a new version of the library and embed into our next release, and watch our firebase stats.

**Comment by tal-mi** [comment]
I will do the tests using "Don't keep activities" in the device developer option to try and mimic behaviour.
Once fix is approved I will release a new NSS wrapper version ASAP.
