### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by mukeshdiscovery** [SAP/gigya-android-sdk#40]
SDK version: gigya-android-sdk-4.0.6

There a many fatal error being reported in firebase Crashlytics with the below exception . Please help us AS SOON AS POSSIBLE

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
       at com.gigya.android.sdk.api.GigyaApiResponse.getErrorDetails(GigyaApiResponse.java:186)
       at com.gigya.android.sdk.network.GigyaError.fromResponse(GigyaError.java:69)
       at com.gigya.android.sdk.api.ApiService$2.onApiSuccess(ApiService.java:188)
       at com.gigya.android.sdk.api.ApiService$1.onResponse(ApiService.java:121)
       at com.gigya.android.sdk.network.adapter.HttpNetworkProvider$GigyaNetworkAsyncTask.onPostExecute(HttpNetworkProvider.java:217)
       at com.gigya.android.sdk.network.adapter.HttpNetworkProvider$GigyaNetworkAsyncTask.onPostExecute(HttpNetworkProvider.java:126)
       at android.os.AsyncTask.finish(AsyncTask.java:771)
       at android.os.AsyncTask.access$900(AsyncTask.java:199)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by mukeshdiscovery** [comment]
@tal-mi Please help AS SOON AS POSSIBLE

**Comment by tal-mi** [comment]
You are using an obsolete version of the SDK. ( gigya-android-sdk-4.0.6).
Please [update](https://github.com/SAP/gigya-android-sdk/releases) your sdk asap.
I will investigate this code section in the latest SDK build regardless.

**Comment by MarineJu** [comment]
Hi @tal-mi ,

We also have lots of this exception increasing our crash rate KPI right now at my company.
Our sdk version is v5.1.4.

Thank you in advance for your investigation / help
Best regards.
Have a nice day.

**Comment by tal-mi** [comment]
It is probable that you are receiving a malformed response.
In any case, this null pointer exception will be handled in the upcoming release.
