### ISSUE TITLE
Opening external link inside screenset crashes

### ISSUE THREAD

**Issue by inovakotnik** [SAP/gigya-android-sdk#55]
Prerequisites:
- Screenset has external links on web page
- User doesn't have browser installed or it's disabled

BUG: Screenset crashes inside GigyaPluginFragment

`FATAL EXCEPTION: main
                                                                                                    Process: com.example.app, PID: 5661
                                                                                                    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.exampleurl.com/... }
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5404)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:754)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5362)
                                                                                                    	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:735)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5748)
                                                                                                    	at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java:1068)
                                                                                                    	at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:324)
                                                                                                    	at androidx.fragment.app.FragmentHostCallback.onStartActivityFromFragment(FragmentHostCallback.java:167)
                                                                                                    	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1445)
                                                                                                    	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1433)
                                                                                                    	at com.gigya.android.sdk.ui.plugin.GigyaPluginFragment$3.onBrowserIntent(GigyaPluginFragment.java:389)
                                                                                                    	at com.gigya.android.sdk.ui.plugin.GigyaPluginWebViewClient.overrideUrlLoad(GigyaPluginWebViewClient.java:80)
                                                                                                    	at com.gigya.android.sdk.ui.plugin.GigyaPluginWebViewClient.shouldOverrideUrlLoading(GigyaPluginWebViewClient.java:36)
                                                                                                    	at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.apk-stable-447211484:14)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:335)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:161)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by inovakotnik** [comment]
@tal-mi Any news about this?

**Comment by tal-mi** [comment]
Will be resolved in next release.
