### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Reply already submitted

### ISSUE THREAD

**Issue by burhanshakir** [SAP/gigya-android-sdk#68]
Run time crash seems to be occurring on Android 13 and up devices. 

gigya-android-sdk v7.0.4
sdk-nss:nss-v1.9.1

Stack trace:

```
Fatal Exception: java.lang.IllegalStateException Reply already submitted
io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:435)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error (MethodChannel.java:268)
com.gigya.android.sdk.nss.bloc.flow.NssFlowManager$1.onError (NssFlowManager.kt:110)
com.gigya.android.sdk.interruption.InterruptionResolverFactory.handleUnsupportedResponse (InterruptionResolverFactory.java:89)
com.gigya.android.sdk.interruption.InterruptionResolverFactory.resolve (InterruptionResolverFactory.java:82)
com.gigya.android.sdk.api.BusinessApiService.handleAccountApiResponse (BusinessApiService.java:101)
com.gigya.android.sdk.api.BusinessApiService$10$1.onApiSuccess (BusinessApiService.java:464)
com.gigya.android.sdk.api.ApiService$1.onResponse (ApiService.java:128)
com.gigya.android.sdk.network.adapter.HttpNetworkProvider$GigyaNetworkAsyncTask.onPostExecute (HttpNetworkProvider.java:246)
com.gigya.android.sdk.network.adapter.HttpNetworkProvider$GigyaNetworkAsyncTask.onPostExecute (HttpNetworkProvider.java:134)
android.os.AsyncTask.finish (AsyncTask.java:771)
android.os.AsyncTask.-$$Nest$mfinish
android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:788)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8757)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

**Comment by farhanfarz** [comment]
We are facing a similar issue when using gigya_flutter_plugin (version 0.1.2), which is possibly causing google to reject our app updates.

Important things to note:
Flutter Version 3.13.9
kotlin_version = '1.9.10'
compileSdkVersion 33
minSdkVersion 29

We are also obfuscating our app using AppDome.

Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(:48)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(:23)
       at com.sap.gigya_flutter_plugin.GigyaSDKWrapper$setAccount$1.onError(:44)
       at z24f845ca.hca9cf951.o0e2c9b34.h311eea58.ofc5cb830.y963f6874$13.onApiSuccess(:38)
       at z24f845ca.hca9cf951.o0e2c9b34.h311eea58.ofc5cb830.kc93327f9$1.onResponse(:122)
       at z24f845ca.hca9cf951.o0e2c9b34.h311eea58.uf788ee3c.ae4b2218e.pa14d9aca$w4ddcb5e1.onPostExecute(:114)
       at z24f845ca.hca9cf951.o0e2c9b34.h311eea58.uf788ee3c.ae4b2218e.pa14d9aca$w4ddcb5e1.onPostExecute(:11)
       at android.os.AsyncTask.finish(AsyncTask.java:771)
       at android.os.AsyncTask.access$900(AsyncTask.java:199)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8292)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
